
function Links(){
    return(
        <div class='relative block w-[100%] max-w-[100%] h-[fit-content]'>
            <h2 class='relative mt-[1%] ml-[2%] italic font-bold'>Links</h2>
            <p class='relative mt-[1%] w-[100%] font-[helvetica] max-w-[100%] pl-[2%] pr-[2%] text-justify'>
            As participants in the Amazon Services LLC Associates Program, we engage in affiliate advertising, 
            which allows us to earn fees by linking to Amazon.com and affiliated sites. [website] may feature links 
            to other websites within content generated by [website] ("[website] Content") or by users ("User-Generated Content"). 
            It's important to note that [website] does not oversee or endorse the content of these third-party websites. By using [website], 
            you acknowledge that [website] holds no responsibility for the availability or content of such third-party websites.
            </p>
        </div>
    )
}
export default Links;